### ISSUE TITLE
Lecteur - échec du lancement

### ISSUE THREAD

**Issue by AMasrar** [PCigales/DLNAmpcRenderer#1]
I used the following command: 
python DLNAmpcRenderer.py -v 2 -p 9100 -m -f -r j

The output is:
Appuyez sur "S" ou fermez mpc pour stopper
Appuyez sur "M" pour activer/désactiver le passage en mode minimisé quand inactif - mode actuel: activé
Appuyez sur "F" pour activer/désactiver le passage en mode plein écran à chaque session - mode actuel: activé
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x81
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x83
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x1
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x5
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x3
27/08/2021 01:13:41 : Création de la fenêtre de contrôle: 1246836
27/08/2021 01:13:41 : Lecteur - lancement
27/08/2021 01:13:41 : Lecteur - échec du lancement
27/08/2021 01:13:41 : Fenêtre de contrôle - message reçu: 0x12

**Comment by AMasrar** [comment]
I've used the new version, there are no more problems with launching mpc. 
Streaming from my pc is working fine "using the right-click menu > cast to device", however I still could not find the renderer in the network, 
I tried the link you provided with my own ip still nothing, tried localhost nothing, next I tried cycling trough the IPs of all my cards, I only got the xml data using the IP of the Hyper-V Virtual Ethernet Adapter

It seems that the script starts the renderer on this specific card, this is why its not accessible from the network, Any ideas how to start it on a specific card?

**Comment by PCigales** [comment]
That's some progress.

I am afraid I am not very familiar with virtualization, so I will not be able to directly solve the problem, but we can find a workaround.

First, we can see that the server managing SSDP m-search requests is working, so there is some hope. 
The choice of the interface used when binding a socket is made by the system, I do not think that Python gives any control on it, so the solution should be to select the right ip, that is the one of the computer on the targeted card.

The host ip address, used for the main server, and communicated to the DLNA clients in advertisements and responses to search requests, is retrieved in the code from line 2443 to 2448. Three ways are successively tried: name resolution, fully qualified name resolution and, as a fallback, connection of a UDP socket and use of its address.

I suggest that you try each of the three methods to see if one of them gives the desired ip address (I guess the third one might be the successful one). Otherwise, you can try to insert an instruction after line 2448 to manuaaly set the ip: "self.ip = '192.168.1.12'" for example to test if thus, the renderer can be reached by other devices from the network.

**Comment by AMasrar** [comment]
The third method worked fine, the only downside to it, is that it needs an internet connection, otherwise it wouldn't get the right IP.
Maybe making the UDP the first method to try will limit this problem when internet is available, also adding an argument to set the IP manually could help when offline.

Thanks for the help.

**Comment by PCigales** [comment]
You are welcome, I am glad for you that it worked.
I am surprised by what you say about the third method needing an internet connection. Is it something you observed or something you suppose ? The targeted ip is the multicast address of the SSDP protocol, on which UPnP relies for discovery, it does not imply any internet communication.
If it is confirmed that this approach works even when the host is offline, I could indeed grant it priority.

**Comment by AMasrar** [comment]
I don't have much background about networking, before I had your answer with the fallback methods, I searched a bit and found the UDP socket method. the only difference is that they used a DNS server instead of the SSDP's multicast address, and they mentioned that it requires an internet connection. this is from where I got the idea to test it offline.

As I don't have physical access to my router right now, I used a mobile hotspot to test the script with no internet, I suspect that it could be the hotspot that did it and not the fact that it being offline.

**Comment by PCigales** [comment]
I understand. I tested the script and the three methods of ip retrieval with my computer only connected to the wifi hotspot run on my Galaxy A8 after having disabled the access to internet on the phone, and everything worked fine. The fact that it failed with your phone may be due to a firmware limitation (lack of support of IGMP ?).

I have brought the changes you suggested to the script and published a new release, if you want to test both the new ip self-retrieval mechanism and the possibility to set manually the ip address to use.

**Comment by AMasrar** [comment]
> I have brought the changes you suggested to the script and published a new release, if you want to test both the new ip self-retrieval mechanism and the possibility to set manually the ip address to use.
Thanks, I tested it. the script is still not able to get my desired ip in every situation, but setting the ip manually solves it.
